### ISSUE TITLE
请问下，我按照配置设置完，但是不显示

### ISSUE THREAD

**Issue by TsukiLiu** [Rabbit-Spec/Surge#10]
![Uploading 407BF54A-3774-488D-835B-A56BD0D137E6_1_105_c.jp
![407BF54A-3774-488D-835B-A56BD0D137E6_1_105_c](https://user-images.githubusercontent.com/44559376/198836730-8c01b995-8cb7-47d3-aa9a-0ea5d6122589.jpg)
eg…]()

**Comment by Rabbit-Spec** [comment]
什么东西按照配置设置完了但是不显示？

**Comment by TsukiLiu** [comment]
[image: IMG_1424.jpg][image: IMG_1423.PNG]
你好，就是机场流量查询

Rabbit-Spec ***@***.***> 于2022年10月30日周日 19:49写道：

**Comment by Rabbit-Spec** [comment]
Hi，首先，不是所有的机场提供的订阅链接都支持流量查询模块。例如TAG机场提供有三个订阅地址，但是经过测试只有其中一个支持流量查询模块。也有可能机场提供的所有订阅链接都不支持。使用该模块请仔细阅读使用说明，机场订阅链接需进行encode后复制到模块的相应位置。
