### ISSUE TITLE
你好，请问有试过淘宝比价能不能正常显示呢？

### ISSUE THREAD

**Issue by mozisen** [Rabbit-Spec/Surge#11]
我用的是surge 5 试了京东的，标准版没有比价信息，但lite版是有通知栏提醒
再试了@yichahucha淘宝的标准版与lite版，都不行，请问一下你那里可以用吗？
可以付费帮指导一下。

**Comment by Rabbit-Spec** [comment]
维护淘宝比价模块的大神很久没有更新过了，目前应该没有可用的淘宝比价模块。个人推荐「什么值得买」这款App，你有什么想买的东西可以去「什么值得买」App里面搜一下。
