### ISSUE TITLE
为什么Surge-CN.conf版有Google.list，而完整版Surge.conf却没有Google.list？

### ISSUE THREAD

**Issue by EchoChan314** [Rabbit-Spec/Surge#12]
完整版不应该更全面吗？

**Comment by Rabbit-Spec** [comment]
你说的对，完整版是应该更全面一些。这些配置代表了不同时期的我的需求，刚开始追求全面，慢慢的删减成了现在用的Mini配置。所以，就没有再针对策略组去维护了，现在基本上都是在优化配置问题。

**Comment by Rabbit-Spec** [comment]
后续等有时间了以后，我会重新维护一下各版本之间的策略组。
