### ISSUE TITLE
macOS翻译模块覆盖了全局

### ISSUE THREAD

**Issue by rayepeng** [Rabbit-Spec/Surge#20]
<img width="600" alt="xxx" src="https://github.com/Rabbit-Spec/Surge/assets/36496433/c1acbf73-813d-4a3b-a734-5cfc08d8c39c">

macOS的翻译模块直接把全局的给覆盖掉了。。我说为啥不生效

**Comment by rayepeng** [comment]
https://github.com/Rabbit-Spec/Surge/pull/21

提了个pr

**Comment by Rabbit-Spec** [comment]
你可以手动复制该模块里的跳过代理到你原本的配置文件里。

**Comment by rayepeng** [comment]
> 你可以手动复制该模块里的跳过代理到你原本的配置文件里。

😓 然鹅我一般都是直接安装模块的hhh，而且一般模块的写法都是要加 append 的吧，不然那就会覆盖用户配置 🫠

**Comment by Rabbit-Spec** [comment]
更新一下模块后再试试
