### ISSUE TITLE
机场流量信息模块

### ISSUE THREAD

**Issue by xuanwohanser** [Rabbit-Spec/Surge#22]
![mmexport1695903574407.jpg](https://github.com/Rabbit-Spec/Surge/assets/85924708/361d0537-be3b-415b-b508-398c96355811)

这样配置之后，显示的是untitled panel。不知道是不是获取的不是带流量的地址encode的。

**Comment by Rabbit-Spec** [comment]
你可以多试几个你机场提供的订阅链接。https://www.urlencoder.org

**Comment by xuanwohanser** [comment]
他是不能用ss的订阅吗，我换了个机场的就可以

**Comment by Rabbit-Spec** [comment]
不一定所有机场的订阅链接都支持的。
