### ISSUE TITLE
TestFlight账户管理这个不兼容mac吗

### ISSUE THREAD

**Issue by ertcds** [Rabbit-Spec/Surge#23]
提示无效模块

**Comment by ertcds** [comment]
> 是的，仅限移动端用。在Mac上装这个要干嘛呀，Mac的软件又不通过TestFlight分发。

多谢，qx那几个当时tf绑定到国区邮箱了。。

**Comment by Rabbit-Spec** [comment]
你更新下模块试试，应该可以安装在macOS上了。但是不保证可以使用。
