### ISSUE TITLE
Steam-All模块检测奈飞好像有点问题

### ISSUE THREAD

**Issue by DockerCS** [Rabbit-Spec/Surge#26]
不能区分奈飞的完整解锁，和自制剧解锁

**Comment by Rabbit-Spec** [comment]
LucaLin233佬的脚本上次更新已经是两年前了，我向他提了issues，我看他仓库上次更新是两周前，应该还在活跃，他修复了以后我这边会第一时间同步。

**Comment by DockerCS** [comment]
> LucaLin233佬的脚本上次更新已经是两年前了，我向他提了issues，我看他仓库上次更新是两周前，应该还在活跃，他修复了以后我这边会第一时间同步。

好的，辛苦了👍

**Comment by Rabbit-Spec** [comment]
模块已经更新，你再试试。
https://raw.githubusercontent.com/Rabbit-Spec/Surge/Master/Module/Panel/Stream-All/Moore/Stream-All.sgmodule

**Comment by DockerCS** [comment]
奈飞还是只能检测出地区，但是检测不出是否完整解锁。

例如下图已经检测出奈飞是台湾地区的，且打☑️了，但是实际上只解锁了自制剧，完全解锁可以播放老友记

![image](https://github.com/Rabbit-Spec/Surge/assets/26867628/7a197222-c398-48d1-bb3e-460efd4808af)
![image](https://github.com/Rabbit-Spec/Surge/assets/26867628/f5d86278-9150-4211-baaa-8194df5fa990)

**Comment by Rabbit-Spec** [comment]
目前没有找到新的解锁检测模块了，大多都还是两年前的。

**Comment by DockerCS** [comment]
> 目前没有找到新的解锁检测模块了，大多都还是两年前的。

https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/streaming-ui-check.js

这个是quantumult X的解锁检测，挺准的，但是不知道怎么改到Surge

**Comment by Rabbit-Spec** [comment]
两个流媒体检测模块都更新了检测资源ID，和QX这个脚本一致了，应该没有问题了，你再试试。我没有只解锁自制的节点无法测试～如果还是不行的话，我也没有什么办法了。

**Comment by Rabbit-Spec** [comment]
理论上和你发的QX脚本检测能力是一致的。

**Comment by Rabbit-Spec** [comment]
怎么样，还有问题吗？

**Comment by DockerCS** [comment]
我这两天测试了一下，应该是没问题了，麻烦您了，多谢多谢

**Comment by Rabbit-Spec** [comment]
好的👌
