### ISSUE TITLE
导入配置报错

### ISSUE THREAD

**Issue by nizaina** [Rabbit-Spec/Surge#27]
大佬，几个链接不管是url导入还下载下来导入都报错
![5925B6AB-B0DA-4A8E-92CA-E3B88FD8EDDD](https://github.com/Rabbit-Spec/Surge/assets/28135753/cf494f12-fbd2-42df-a5ff-63c0d3a4bee2)
![4198D415-982C-4B7D-96B1-618C7FBE398C](https://github.com/Rabbit-Spec/Surge/assets/28135753/91225703-affd-4f8b-b971-345ee0c53367)
![AC8C2195-7FF3-47E3-B9C1-18D9E560CB8A](https://github.com/Rabbit-Spec/Surge/assets/28135753/7b2e0cff-6f0d-4e72-88a7-1e02fa039330)

**Comment by Rabbit-Spec** [comment]
你Surge的版本太低了，需要 5.11.1 或更新版本。

更新至 5.11.1 或更新版本后还导入不了的话，请确认Surge订阅是否到期，有没有解锁“Smart策略组”功能。
