### ISSUE TITLE
surge配置

### ISSUE THREAD

**Issue by liang609938457** [Rabbit-Spec/Surge#28]

**Comment by Rabbit-Spec** [comment]
怎么了？

**Comment by MingKuanWu** [comment]
请问最近请求页面，不显示域名。是设置的问题吗![image](https://github.com/user-attachments/assets/3607845d-dd08-46f0-a4ab-111e07b2f0e7)

**Comment by Rabbit-Spec** [comment]
> 请问最近请求页面，不显示域名。是设置的问题吗![image](https://private-user-images.githubusercontent.com/105577485/357132432-3607845d-dd08-46f0-a4ab-111e07b2f0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTM0MjAsIm5iZiI6MTcyMzUxMzEyMCwicGF0aCI6Ii8xMDU1Nzc0ODUvMzU3MTMyNDMyLTM2MDc4NDVkLWRkMDgtNDZmMC1hNGFiLTExMWUwN2IyZjBlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwMTM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2I5YTY1YmRkMTNhZDg4YmUyODJhNTE1ZTQ4NWI2NDVkMTMwZTQ3YjBmNmI4MGUyNGMyNzkwYmIyZmQyYWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.646URo36Quy1346F7GoO3glEE_oZUIHKWpIyPTARhUU)

tg显示IP但不显示域名是正常的。

**Comment by MingKuanWu** [comment]
> > 请问最近请求页面，不显示域名。是设置的问题吗![image](https://private-user-images.githubusercontent.com/105577485/357132432-3607845d-dd08-46f0-a4ab-111e07b2f0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTM0MjAsIm5iZiI6MTcyMzUxMzEyMCwicGF0aCI6Ii8xMDU1Nzc0ODUvMzU3MTMyNDMyLTM2MDc4NDVkLWRkMDgtNDZmMC1hNGFiLTExMWUwN2IyZjBlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwMTM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2I5YTY1YmRkMTNhZDg4YmUyODJhNTE1ZTQ4NWI2NDVkMTMwZTQ3YjBmNmI4MGUyNGMyNzkwYmIyZmQyYWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.646URo36Quy1346F7GoO3glEE_oZUIHKWpIyPTARhUU)
> 
> 
> 
> tg显示IP但不显示域名是正常的。

好的 谢谢
