### ISSUE TITLE
应用配置访问tiktok失败

### ISSUE THREAD

**Issue by laowhites** [Rabbit-Spec/Surge#29]
背景
1.使用该配置可以访问网页版tiktok，ap版本失败
2.排除节点问题（通过使用不同配置文件对比验证）

**Comment by laowhites** [comment]
复现步骤
1.surge安装连接配置  https://raw.githubusercontent.com/Rabbit-Spec/Surge/Master/Conf/Spec/Surge.conf 
2.修改订阅链接
3.启动surge
4.打开tiktok，滑动浏览内容会刷不出内容，点进直播间，会提示链接不稳定，自动退出直播间
5.在上述场景下，用浏览器打看tiktok，正常使用，无问题
<img width="365" alt="image" src="https://github.com/user-attachments/assets/13178eb9-d3c7-48ca-9f32-ad951583b2f0">

**Comment by laowhites** [comment]
如果在surge中，不使用上述comment中提及的配置，使用机场直接提供的的配置，ap和浏览器都正常使用

**Comment by Rabbit-Spec** [comment]
无法观看的App是iOS的Tiktok客户端还是Android的Tiktok客户端？

**Comment by laowhites** [comment]
> 无法观看的App是iOS的Tiktok客户端还是Android的Tiktok客户端？

Ios

**Comment by Rabbit-Spec** [comment]
最近请求看看是否正常。
