### ISSUE TITLE
I cann't login to surge.

### ISSUE THREAD

**Issue by arman-ebrahimi** [Rabbit-Spec/Surge#3]
When I run 'surge' in cmd, it asks for my email and I enter my email. Then it asks for my password, but when I enter my password, nothing happens.
![Screenshot (25)](https://user-images.githubusercontent.com/71581781/182085897-9ea99751-ad59-4d8c-bf5f-f159e91a825f.png)

**Comment by Rabbit-Spec** [comment]
Surge refers to surge VPN software on IOS / iPadOS / macOS and other operating systems.
