### ISSUE TITLE
卡片模式不显示图片

### ISSUE THREAD

**Issue by ydoupo** [Rabbit-Spec/Surge#30]
用的是带图片链接的完整版配置，但是不显示图片，今天刚升级付费最新版的surge ios，如图，
![IMG_2186](https://github.com/user-attachments/assets/d108e0a4-ce59-475c-847a-23273fe367e7)
![IMG_2187](https://github.com/user-attachments/assets/723a795b-425e-43b2-a1f1-6c32806e35b0)

还有surge mac 也不显示图标的图片

谢谢解惑

**Comment by Rabbit-Spec** [comment]
1. 你的Surge for iOS是否为5.12.0（3284）版本？

2. Surge for Mac目前是不支持icon的。

**Comment by ydoupo** [comment]
> 1. 你的Surge for iOS是否为5.12.0（3284）版本？
> 2. Surge for Mac目前是不支持icon的。

哦哦，没有升级到最新版，谢谢🙏

**Comment by Rabbit-Spec** [comment]
好的👌
