### ISSUE TITLE
分流规则中能否将"台湾"策略组添加进来？

### ISSUE THREAD

**Issue by mryee2023** [Rabbit-Spec/Surge#31]
可否在分流规则中能否将"台湾"策略组添加进来？
当然，我自行添加也是可以的，但是更新到最新的配置又得做一遍这样的操作。
谢谢

**Comment by Rabbit-Spec** [comment]
我会考虑你的建议并在下个版本上增加台湾策略组到其他分流策略组里。
因为台湾节点使用的人很少，绝大多数是为了看B站，所以没有将台湾策略组加到其他的分流策略组里。
