### ISSUE TITLE
正式版surge能否使用？

### ISSUE THREAD

**Issue by Wanvy-MN** [Rabbit-Spec/Surge#33]
根据blackmatrix7的规则说明，*_All.list（如：ChinaMax_All_No_Resolve.list）规则需要Surge 5.21.0(2952) 以上版本使用，现在正式版才5.13，所以是你的配置是不是只能testflight版本才能用，正式版不能用？

**Comment by Rabbit-Spec** [comment]
正式版Surge可以用。
5.21.0(2952) 没正式版 5.13.0(3310)版本新。以括号内的版本高低为准。
