### ISSUE TITLE
国内域名 ip 解析异常

### ISSUE THREAD

**Issue by zscorpio** [Rabbit-Spec/Surge#36]
<img width="488" alt="image" src="https://github.com/user-attachments/assets/dfa6b022-bcba-48bd-8c7b-f59b732d5053">

163.181.35.248:443 (img.alicdn.com)
测试的时候发现有时候淘宝的域名会解析到国外, 想咨询下这个应该怎么处理?
看了下 dns 配置, 好像是对的

**Comment by Rabbit-Spec** [comment]
163.181.35.248这个IP归属地就是香港，没有问题呀。规则策略也走了直连。

**Comment by zscorpio** [comment]
不好意思, 我可能没有表述清楚, 我重新整理一下, 使用过程中, 有时候国内网站也会有点慢, 举个例子的话, 就是上面这个 ip.
我更换了一台国内的服务器 无代理, 
<img width="614" alt="image" src="https://github.com/user-attachments/assets/a6ef8829-282b-44c2-97fe-59e8cdc674ef">
<img width="427" alt="image" src="https://github.com/user-attachments/assets/bc33d778-cd4c-4bf0-b552-2f67b84b0c2a">
这个好像是我逛闲鱼还是淘宝的时候, 发现图片出来很慢, 然后看请求, 发现解析到了国外 ip, 其实国内的网站应该解析到国内的 ip.
这一块规则不是很熟悉, 今天也找了一些教程, 大概知道原因, 不是很确定, https://www.nodeseek.com/post-53989-1
我最后是按照这个说明, 
```
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaMax/ChinaMax_All.list,"🌐 全球直连",no-resolve,extended-matching
``` 

加了一个 no-resolve, 清空 DNS 顺便测试了下, 看起来好像是解析到了国内
所以想找你咨询下, 看是否应该这样配置, 我简单的理解, 是不是应该直连的走国内 ip , 还没特别搞明白原理
