### ISSUE TITLE
节点ip模块建议增加ipv6显示功能

### ISSUE THREAD

**Issue by gamekiller0010** [Rabbit-Spec/Surge#4]
https://github.com/Rabbit-Spec/Surge/tree/Master/Panel/IP-Check/
建议增加ipv6显示功能

**Comment by Rabbit-Spec** [comment]
现在机场基本都不支持v6，如果想看本地网络v6情况的话可以用这个模块。
https://github.com/Rabbit-Spec/Surge/tree/Master/Module/Panel/Network-Info
