### ISSUE TITLE
代理测速可以更换成 gstatic 或者 cloudflare

### ISSUE THREAD

**Issue by taurusxin** [Rabbit-Spec/Surge#6]
现在配置文件中的 http://1.1.1.1/generate_204 已经301到主站

<img width="1216" alt="iShot_2022-08-27_10 56 06" src="https://user-images.githubusercontent.com/17809960/187011666-a774a923-a53e-41a9-940f-a3c407566e14.png">

**Comment by Rabbit-Spec** [comment]
部分机场会劫持（http://www.gstatic.com/generate_204），显示国内延迟。所以用的(http://1.1.1.1/generate_204)。
