### ISSUE TITLE
微博搜索页看不到热搜

### ISSUE THREAD

**Issue by johnzhang803** [Rabbit-Spec/Surge#8]
![09D027CA-DF7A-4EE7-886A-DDB6390A6819](https://user-images.githubusercontent.com/34101845/190050020-0c1fbb61-9314-48d3-8ee4-e9af155c73af.png)

**Comment by Rabbit-Spec** [comment]
Hi，作者新版本的这款模块就是如此，如果要查看更多热搜的话，可以点击「推荐词条」下面的更多热搜。
