### ISSUE TITLE
你好就是配置信息添加后，如果有2个机场就会只显示1个

### ISSUE THREAD

**Issue by TsukiLiu** [Rabbit-Spec/Surge#9]
![IMG_1258](https://user-images.githubusercontent.com/44559376/190891044-d8b037ef-2f07-4896-af09-82ef91ec4a12.PNG)

**Comment by Rabbit-Spec** [comment]
Hi，你好。这个需要修改该模块的脚本名字，最简单的就是在下面三个Sub_info后面加个1变成Sub_info1。

[Panel]
Sub_info = script-name=Sub_info,update-interval=3600

[Script]
Sub_info

**Comment by TsukiLiu** [comment]
好的，已经弄出来了，感谢回复

**Comment by Rabbit-Spec** [comment]
好哒～
